### ISSUE TITLE
Joining the sequences

### ISSUE THREAD

**Issue by AbhishekJambure** [AbhishekJambure/HacktoberFest#1]
Suppose there are two sequences S1 and S2. Both starts with three digit number, then the next term of the sequence will be the addition of the last term and digits in the last term. Write a Java program to find the joining point of the two Sequences.
E.g. Input :	471
			480
	Output :  519

**Comment by PrasadMulherkar** [comment]
Hey, I have a java code that can solve your issue, assign it to me.

**Comment by AbhishekJambure** [comment]
Ok, I'm assigning to you!
